package models;

import java.util.List;
import java.util.Map;

/**
 * Created with IntelliJ IDEA.
 * User: liclu
 * Date: 13-7-19
 * Time: 下午10:30
 * To change this template use File | Settings | File Templates.
 */
public class PatientsResults {
    private int id;
    private String name; // for example , Compare with 18 to 30 ages
    private String datetime; // when generate the result
    private List<AreaData> areaDataList; // storage the data that generated by external program





    public PatientsResults(String name, List<AreaData> areaDataList) {
        this.name = name;
        this.areaDataList = areaDataList;
    }




}
